# Generated by Django 4.1.7 on 2023-03-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, verbose_name='Название услуги')),
                ('name', models.CharField(max_length=250, verbose_name='Имена сотрудников')),
                ('info', models.TextField(verbose_name='информация про услугу и сотрдника')),
            ],
        ),
    ]
