# Generated by Django 4.1.7 on 2023-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikles',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='artikles',
            name='prise',
            field=models.TextField(default=0, max_length=250, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artikles',
            name='info',
            field=models.TextField(max_length=250, verbose_name='информация про услугу и сотрдника'),
        ),
        migrations.AlterField(
            model_name='artikles',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Имя сотрудника'),
        ),
    ]
