# Generated by Django 4.1.7 on 2023-03-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0004_coment_alter_artikles_prise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikles',
            options={},
        ),
        migrations.RemoveField(
            model_name='coment',
            name='coment',
        ),
        migrations.RemoveField(
            model_name='coment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='coment',
            name='estimation',
        ),
        migrations.AlterField(
            model_name='artikles',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='artikles',
            name='info',
            field=models.TextField(max_length=250, null=True, verbose_name='информация про услугу и сотрдника'),
        ),
        migrations.AlterField(
            model_name='artikles',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='artikles',
            name='prise',
            field=models.CharField(max_length=10, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='artikles',
            name='service',
            field=models.CharField(max_length=20, null=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='service',
            field=models.CharField(max_length=20, null=True, verbose_name='Название услуги'),
        ),
    ]
