# Generated by Django 4.1.7 on 2023-03-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0005_alter_artikles_options_remove_coment_coment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='comm',
            field=models.CharField(max_length=100, null=True, verbose_name='оставте коментарий'),
        ),
    ]
