# Generated by Django 4.1.7 on 2023-03-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0006_coment_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coment',
            old_name='comm',
            new_name='coment',
        ),
    ]
