# Generated by Django 4.1.7 on 2023-03-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0007_rename_comm_coment_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coment',
            old_name='coment',
            new_name='comm',
        ),
    ]
