# Generated by Django 4.1.7 on 2023-03-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0008_rename_coment_coment_comm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikles',
            name='image',
        ),
    ]
