# Generated by Django 4.1.7 on 2023-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0009_remove_artikles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='comm',
        ),
        migrations.AddField(
            model_name='artikles',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='фото'),
        ),
    ]
