# Generated by Django 4.1.7 on 2023-03-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0011_remove_artikles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikles',
            name='info',
            field=models.TextField(max_length=250, null=True, verbose_name='Информация про услугу и сотрдника'),
        ),
        migrations.AlterField(
            model_name='artikles',
            name='prise',
            field=models.CharField(max_length=10, null=True, verbose_name='Цена'),
        ),
    ]
