# Generated by Django 4.1.7 on 2023-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0012_alter_artikles_info_alter_artikles_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='comm',
            field=models.CharField(max_length=50, null=True, verbose_name='Ваш коментарий'),
        ),
    ]
