# Generated by Django 4.1.7 on 2023-04-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0013_coment_comm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='artikles',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
    ]
