# Generated by Django 4.1.7 on 2023-04-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0014_mymodel_alter_artikles_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
