# Generated by Django 4.1.7 on 2023-04-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0017_rename_favorite_fruit_coment_comm_coment_fruit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='fruit',
            field=models.CharField(max_length=50, null=True, verbose_name='ваш a'),
        ),
    ]
