# Generated by Django 4.1.7 on 2023-04-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0019_alter_coment_fruit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coment',
            old_name='fruit',
            new_name='prise',
        ),
    ]
