# Generated by Django 4.1.7 on 2023-04-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datebase', '0020_rename_fruit_coment_prise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='prise',
        ),
    ]
